export enum Biome {
  Ocean = 'ocean',
  Water = 'water',
  Beach = 'beach',
  Rock = 'rock',
  Tundra = 'tundra',
  Alpine = 'alpine',
  AlpineGrassland = 'alpine grassland',
  Taiga = 'taiga',
  Desert = 'desert',
  Rainforest = 'rainforest',
  Grassland = 'grassland',
  Woodland = 'woodland',
  Forest = 'forest',
}