export enum FamilyRole {
    Head = "head",
    Patriarch = "patriarch",
    Matriarch = "matriarch",
    Heir = "heir",
    MerchantPrince = "merchant_prince",
    MerchantPrincess = "merchant_princess",
    Advisor = "advisor",
    Seneschal = "seneschal",
    Physician = "physician",
    Champion = "champion",
    Tutor = "tutor",
    Nurse = "nurse",
    Architect = "architect",
    Alchemist = "alchemist",
    Cook = "cook",
    Gardener = "gardener",
    Emissary = "emissary",
    Chronicler = "chronicler",
    Kenneler = "kenneler"
  }