export enum FloraType {

  // --- Ocean ---
  GiantKelp = 'giant_kelp',
  BullKelp = 'bull_kelp',
  SugarKelp = 'sugar_kelp',
  Wakame = 'wakame',
  Nori = 'nori',
  Sargassum = 'sargassum',
  Eelgrass = 'eelgrass',
  Bladderwrack = 'bladderwrack',
  IrishMoss = 'irish_moss',
  SeaLettuce = 'sea_lettuce',
  RedAlgae = 'red_algae',
  CorallineAlgae = 'coralline_algae',
  SeaPalm = 'sea_palm',
  FeatherBoaKelp = 'feather_boa_kelp',
  BrownAlgae = 'brown_algae',
  BlueGreenAlgae = 'blue_green_algae',
  MarinePhytoplankton = 'marine_phytoplankton',
  SeaMoss = 'sea_moss',
  Rockweed = 'rockweed',
  DriftAlgaeMats = 'drift_algae_mats',

    // --- Freshwater (Water biome) ---
  WaterLily = 'water_lily',
  Duckweed = 'duckweed',
  WaterHyacinth = 'water_hyacinth',
  Cattails = 'cattails',
  Reeds = 'reeds',
  Pondweed = 'pondweed',
  WaterMilfoil = 'water_milfoil',
  Hornwort = 'hornwort',
  Lotus = 'lotus',
  Frogbit = 'frogbit',
  Pickerelweed = 'pickerelweed',
  Arrowhead = 'arrowhead',
  Bulrush = 'bulrush',
  MarshMarigold = 'marsh_marigold',
  WaterChestnut = 'water_chestnut',
  TapeGrass = 'tape_grass',
  Elodea = 'elodea',
  FreshwaterAlgae = 'freshwater_algae',
  WaterMoss = 'water_moss',
  FloatingFern = 'floating_fern',

  // --- Beach ---
  BeachGrass = 'beach_grass',
  SeaOats = 'sea_oats',
  BeachMorningGlory = 'beach_morning_glory',
  DuneSunflower = 'dune_sunflower',
  SeaPea = 'sea_pea',
  SeaLavender = 'sea_lavender',
  SeaRocket = 'sea_rocket',
  Glasswort = 'glasswort',
  Saltwort = 'saltwort',
  BeachRose = 'beach_rose',
  IcePlant = 'ice_plant',
  SandVerbena = 'sand_verbena',
  CoastalSedge = 'coastal_sedge',
  BeachHeather = 'beach_heather',
  SeaHolly = 'sea_holly',
  Saltbush = 'saltbush',
  SeasideGoldenrod = 'seaside_goldenrod',
  CoastalSage = 'coastal_sage',
  DuneGrass = 'dune_grass',
  CoastalRosemary = 'coastal_rosemary',

  // --- Rock ---
  Lichen = 'lichen',
  RockMoss = 'rock_moss',
  RockFern = 'rock_fern',
  Stonecrop = 'stonecrop',
  Saxifrage = 'saxifrage',
  CliffGrass = 'cliff_grass',
  RockCress = 'rock_cress',
  Sedum = 'sedum',
  CushionPlant = 'cushion_plant',
  WallRue = 'wall_rue',
  RockPurslane = 'rock_purslane',
  CliffDaisy = 'cliff_daisy',
  RockBellflower = 'rock_bellflower',
  CliffSpurge = 'cliff_spurge',
  RockThyme = 'rock_thyme',
  EndolithicAlgae = 'endolithic_algae',
  RockOnion = 'rock_onion',
  WildChives = 'wild_chives',
  RockBarley = 'rock_barley',
  MountainSorrel = 'mountain_sorrel',

  // --- Tundra ---
  ArcticMoss = 'arctic_moss',
  ReindeerLichen = 'reindeer_lichen',
  ArcticWillow = 'arctic_willow',
  DwarfBirch = 'dwarf_birch',
  CottonGrass = 'cotton_grass',
  PurpleSaxifrage = 'purple_saxifrage',
  ArcticPoppy = 'arctic_poppy',
  MountainAvens = 'mountain_avens',
  Bearberry = 'bearberry',
  SnowButtercup = 'snow_buttercup',
  ArcticLupine = 'arctic_lupine',
  Crowberry = 'crowberry',
  MossCampion = 'moss_campion',
  BogRosemary = 'bog_rosemary',
  Cloudberry = 'cloudberry',
  AlpineBistort = 'alpine_bistort',
  ArcticSedge = 'arctic_sedge',
  PolarGrass = 'polar_grass',
  ArcticBluegrass = 'arctic_bluegrass',
  TundraHeather = 'tundra_heather',

   // ===== ALPINE =====
  Edelweiss = 'edelweiss',
  AlpineGentian = 'alpine_gentian',
  AlpineForgetMeNot = 'alpine_forget_me_not',
  AlpineButtercup = 'alpine_buttercup',
  AlpineCushionPlant = 'alpine_cushion_plant',
  AlpinePoppy = 'alpine_poppy',
  SnowLotus = 'snow_lotus',
  AlpineSaxifrage = 'alpine_saxifrage',
  DwarfJuniper = 'dwarf_juniper',
  AlpineThyme = 'alpine_thyme',
  AlpineAster = 'alpine_aster',
  AlpinePrimrose = 'alpine_primrose',
  AlpineCampion = 'alpine_campion',
  AlpineSorrel = 'alpine_sorrel',
  RockJasmine = 'rock_jasmine',
  AlpineMoss = 'alpine_moss',
  AlpinePlantain = 'alpine_plantain',
  AlpineValerian = 'alpine_valerian',
  AlpineRue = 'alpine_rue',
  AlpineYarrow = 'alpine_yarrow',

  // ===== ALPINE GRASSLAND =====
  AlpineBluegrass = 'alpine_bluegrass',
  FescueGrass = 'fescue_grass',
  TuftedHairgrass = 'tufted_hairgrass',
  AlpineClover = 'alpine_clover',
  AlpineDaisy = 'alpine_daisy',
  AlpineSage = 'alpine_sage',
  AlpineBistortGrassland = 'alpine_bistort_grassland',
  AlpineViolet = 'alpine_violet',
  AlpinePhlox = 'alpine_phlox',
  AlpineCranesbill = 'alpine_cranesbill',
  AlpineHawkweed = 'alpine_hawkweed',
  AlpineMilkvetch = 'alpine_milkvetch',
  AlpineYarrowGrassland = 'alpine_yarrow_grassland',
  AlpinePlantainGrassland = 'alpine_plantain_grassland',
  AlpineSedgeGrassland = 'alpine_sedge_grassland',
  AlpineTimothy = 'alpine_timothy',
  AlpineRyegrass = 'alpine_ryegrass',
  AlpineMeadowButtercup = 'alpine_meadow_buttercup',
  AlpineWildOnion = 'alpine_wild_onion',
  AlpineMeadowSorrel = 'alpine_meadow_sorrel',

  // ===== TAIGA =====
  Spruce = 'spruce',
  Pine = 'pine',
  Fir = 'fir',
  Larch = 'larch',
  FeatherMoss = 'feather_moss',
  LabradorTea = 'labrador_tea',
  Lingonberry = 'lingonberry',
  Blueberry = 'blueberry',
  BogCranberry = 'bog_cranberry',
  CloudberryTaiga = 'cloudberry_taiga',
  BearberryTaiga = 'bearberry_taiga',
  WillowShrub = 'willow_shrub',
  DwarfBirchTaiga = 'dwarf_birch_taiga',
  Horsetail = 'horsetail',
  Clubmoss = 'clubmoss',
  Wintergreen = 'wintergreen',
  PineGrass = 'pine_grass',
  BogSedge = 'bog_sedge',
  TaigaMushrooms = 'taiga_mushrooms',
  ResinPine = 'resin_pine',

    // ===== DESERT =====
  SaguaroCactus = 'saguaro_cactus',
  PricklyPear = 'prickly_pear',
  BarrelCactus = 'barrel_cactus',
  ChollaCactus = 'cholla_cactus',
  CreosoteBush = 'creosote_bush',
  JoshuaTree = 'joshua_tree',
  Mesquite = 'mesquite',
  DesertSage = 'desert_sage',
  Yucca = 'yucca',
  Agave = 'agave',
  Ocotillo = 'ocotillo',
  Brittlebush = 'brittlebush',
  DesertMarigold = 'desert_marigold',
  DesertLupine = 'desert_lupine',
  DesertPoppy = 'desert_poppy',
  SaltDesertbush = 'salt_desertbush',
  DesertGrass = 'desert_grass',
  Aloe = 'aloe',
  IceDesertPlant = 'ice_desert_plant',
  SandVerbenaDesert = 'sand_verbena_desert',

  // ===== RAINFOREST =====
  KapokTree = 'kapok_tree',
  Mahogany = 'mahogany',
  RubberTree = 'rubber_tree',
  StranglerFig = 'strangler_fig',
  FigTreeRainforest = 'fig_tree_rainforest',
  BananaPlant = 'banana_plant',
  CocoaTree = 'cocoa_tree',
  CoffeePlant = 'coffee_plant',
  Orchids = 'orchids',
  Bromeliads = 'bromeliads',
  Heliconia = 'heliconia',
  BambooRainforest = 'bamboo_rainforest',
  TreeFern = 'tree_fern',
  Lianas = 'lianas',
  MossRainforest = 'moss_rainforest',
  Epiphytes = 'epiphytes',
  PitcherPlant = 'pitcher_plant',
  VanillaOrchid = 'vanilla_orchid',
  PalmTree = 'palm_tree',
  MedicinalVines = 'medicinal_vines',

  // ===== GRASSLAND =====
  PrairieGrass = 'prairie_grass',
  BuffaloGrass = 'buffalo_grass',
  Switchgrass = 'switchgrass',
  BigBluestem = 'big_bluestem',
  LittleBluestem = 'little_bluestem',
  RyeGrass = 'rye_grass',
  WildOats = 'wild_oats',
  GrasslandClover = 'grassland_clover',
  Dandelion = 'dandelion',
  Milkweed = 'milkweed',
  PrairieSunflower = 'prairie_sunflower',
  Goldenrod = 'goldenrod',
  Coneflower = 'coneflower',
  PrairieViolet = 'prairie_violet',
  WildCarrot = 'wild_carrot',
  PrairieSage = 'prairie_sage',
  Thistle = 'thistle',
  Chicory = 'chicory',
  PrairieLupine = 'prairie_lupine',
  TallGrassMix = 'tall_grass_mix',

  // ===== WOODLAND =====
  Oak = 'oak',
  Birch = 'birch',
  Maple = 'maple',
  Aspen = 'aspen',
  Hazel = 'hazel',
  Hawthorn = 'hawthorn',
  Rowan = 'rowan',
  Elderberry = 'elderberry',
  Brambles = 'brambles',
  WoodlandFerns = 'woodland_ferns',
  WoodlandMoss = 'woodland_moss',
  WildGarlic = 'wild_garlic',
  Bluebells = 'bluebells',
  WoodAnemone = 'wood_anemone',
  Ivy = 'ivy',
  Honeysuckle = 'honeysuckle',
  WoodlandGrass = 'woodland_grass',
  Dogwood = 'dogwood',
  Serviceberry = 'serviceberry',
  WoodlandSedge = 'woodland_sedge',

  // ===== FOREST =====
  ForestOak = 'forest_oak',
  ForestPine = 'forest_pine',
  Beech = 'beech',
  ForestMaple = 'forest_maple',
  Cedar = 'cedar',
  ForestSpruce = 'forest_spruce',
  ForestFir = 'forest_fir',
  Hemlock = 'hemlock',
  ForestFerns = 'forest_ferns',
  ForestMoss = 'forest_moss',
  ForestLichens = 'forest_lichens',
  UnderstoryShrubs = 'understory_shrubs',
  Holly = 'holly',
  Yew = 'yew',
  ForestIvy = 'forest_ivy',
  Bracken = 'bracken',
  WildMushroomsForest = 'wild_mushrooms_forest',
  ForestWildflowers = 'forest_wildflowers',
  ForestGrass = 'forest_grass',
  CanopyVines = 'canopy_vines',

    // ===== STORM REEFS =====
  LightningKelp = 'lightning_kelp',
  StormVines = 'storm_vines',
  ThunderBlossom = 'thunder_blossom',
  ShockMoss = 'shock_moss',
  ConductiveCoral = 'conductive_coral',
  StaticReeds = 'static_reeds',
  StormLichen = 'storm_lichen',
  VoltBloom = 'volt_bloom',
  CapacitorPods = 'capacitor_pods',
  GravityAnchors = 'gravity_anchors',

  // ===== SKY MEADOWS =====
  SkyGrass = 'sky_grass',
  CloudClover = 'cloud_clover',
  Windflower = 'windflower',
  FeatherReeds = 'feather_reeds',
  DriftThistle = 'drift_thistle',
  Sunpetal = 'sunpetal',
  AerialSedge = 'aerial_sedge',
  SkyWheat = 'sky_wheat',
  FloatBloom = 'float_bloom',
  ZephyrHerbs = 'zephyr_herbs',

  // ===== CLOUD FORESTS =====
  MistwoodTree = 'mistwood_tree',
  VaporMoss = 'vapor_moss',
  RaincatchVines = 'raincatch_vines',
  FloatingOrchids = 'floating_orchids',
  CloudFerns = 'cloud_ferns',
  DewleafShrubs = 'dewleaf_shrubs',
  SkyFig = 'sky_fig',
  FogLianas = 'fog_lianas',
  NimbusIvy = 'nimbus_ivy',
  CondenserBromeliads = 'condenser_bromeliads',

  // ===== SUBTERRANEAN WETLANDS =====
  CaveReeds = 'cave_reeds',
  BlindLotus = 'blind_lotus',
  RootKelp = 'root_kelp',
  SporeCattails = 'spore_cattails',
  GlowAlgae = 'glow_algae',
  MudFerns = 'mud_ferns',
  FilterMoss = 'filter_moss',
  DripVines = 'drip_vines',
  SiltWillow = 'silt_willow',
  BogLanterns = 'bog_lanterns',

  // ===== CRYSTAL GROTTOS =====
  QuartzBloom = 'quartz_bloom',
  PrismFern = 'prism_fern',
  ResonantRoots = 'resonant_roots',
  CrystalVines = 'crystal_vines',
  LatticeMoss = 'lattice_moss',
  ManaBud = 'mana_bud',
  HarmonicLichen = 'harmonic_lichen',
  FacetFlowers = 'facet_flowers',
  LightDrinkingIvy = 'light_drinking_ivy',
  SingingCrystals = 'singing_crystals',

  // ===== FUNGAL FORESTS =====
  Towercaps = 'towercaps',
  ShelfFungus = 'shelf_fungus',
  MyceliumMats = 'mycelium_mats',
  SporeReeds = 'spore_reeds',
  Glowshrooms = 'glowshrooms',
  VeilMold = 'veil_mold',
  RootFungus = 'root_fungus',
  PuffballClusters = 'puffball_clusters',
  CordycepsBloom = 'cordyceps_bloom',
  FungalVines = 'fungal_vines',

  // ===== ASHEN DEEPS =====
  AshFerns = 'ash_ferns',
  EmberBulbs = 'ember_bulbs',
  Charroot = 'charroot',
  LavaMoss = 'lava_moss',
  CinderShrubs = 'cinder_shrubs',
  BasaltReeds = 'basalt_reeds',
  PyreLichen = 'pyre_lichen',
  SmolderVines = 'smolder_vines',
  HeatBloom = 'heat_bloom',
  ObsidianKelp = 'obsidian_kelp'

}
