export enum Trait {
    Ambitious = "Ambitious",
    Adventurous = "Adventurous",
    Astute = "Astute",
    Charismatic = "Charismatic",
    Cunning = "Cunning",
    Deceitful = "Deceitful",
    Diligent = "Diligent",
    Disciplined = "Disciplined",
    Frugal = "Frugal",
    Generous = "Generous",
    Honest = "Honest",
    Industrious = "Industrious",
    Loyal = "Loyal",
    Mercenary = "Mercenary",
    Patient = "Patient",
    Pragmatic = "Pragmatic",
    Resourceful = "Resourceful",
    Ruthless = "Ruthless",
    StrongWilled = "StrongWilled",
    Stubborn = "Stubborn",
    Temperance = "Temperance",
    Thrifty = "Thrifty",
    Zealous = "Zealous",

    Strong = "Strong",
    Agile = "Agile",
    Hardy = "Hardy",
    Resilient = "Resilient",
    Tough = "Tough",

    EdgedWeapons = "EdgedWeapons",
    ImpactWeapons = "ImpactWeapons",
    FlailWeapons = "FlailWeapons",
    PolearmWeapons = "PolearmWeapons",
    ThrownWeapons = "ThrownWeapons",
    BowWeapons = "BowWeapons",
    MissileDevices = "MissileDevices",

    Charming = "Charming",
    Eloquent = "Eloquent",
    Gregarious = "Gregarious",
    Hospitable = "Hospitable",
    Popular = "Popular",
    Respectful = "Respectful",
    Sociable = "Sociable",

    Clever = "Clever",
    Creative = "Creative",
    Curious = "Curious",
    Erudite = "Erudite",
    Insightful = "Insightful",
    Intuitive = "Intuitive",
    Learned = "Learned",
    Logical = "Logical",
    Observant = "Observant",
    Shrewd = "Shrewd",
    Wise = "Wise",

    Devout = "Devout",
    Pious = "Pious",
    Skeptical = "Skeptical",
    Heretical = "Heretical",

    Cosmopolitan = "Cosmopolitan",
    Traditionalist = "Traditionalist",
    Patriotic = "Patriotic",
    Xenophobic = "Xenophobic",

    Merchant = "Merchant",
    Craftsman = "Craftsman",
    Alchemist = "Alchemist",
    Philosopher = "Philosopher",  
    Sailor = "Sailor",
    Leader = "Leader",
    Explorer = "Explorer",
    Diplomat = "Diplomat",
    Pirate = "Pirate",
    Usurer = "Usurer",
    GuildMaster = "GuildMaster",

    Pregnant = "pragnant",
    Married = "married",
    Bastard = "bastard",
  }