export  enum SettlementType {
    Hamlet = "hamlet",
    Village = "village",
    TradingPost = "trading_post",
    Town = "town",
    City = "city",
    Metropolis = "metropolis",
    Capital = "capital",
    Fortress = "fortress",
    TradeHub = "TradeHub",
    Tribe = "tribe",
    Lighthouse = "lighthouse",
    Ruins = "ruins",
    AncientRuins = "ancient_ruins",
    UndergroundCity = "underground_city",
    FloatingCity = "floating_city",
    PhasingCity = "phasing_city",
  }