export enum ShipType {
    Raft = "raft",
    Snaikka = "snaikka",
    Crayer = "crayer",
    Sloop = "sloop",
    Kogge = "kogge",
    Schoener = "schoener",
    Brig = "brig",    
    Hulk = "hulk",
    Corvette = "Corvette",
    Fluyt = "fluyt",
    Caravel = "caravel",
    Frigate = "frigate",
    Galleon = "galleon",
    Airship = "airship",
    FloatingJuggernaut = "floating_juggernaut",
    Submersible = "submersible",
    Turtle = "turtle",
    Ghostship = "ghostship",    
  }