export enum StructureEffect {
    // Multipliers
    ProsperityMultiplier = "prosperity_multiplier",
    HappinessMultiplier = "happiness_multiplier",
    ReputationMultiplier = "reputation_multiplier",
    PopulationGrowthMultiplier = "population_growth_multiplier",
    HousingMultiplier = "housing_multiplier",
    StorageMultiplier = "storage_multiplier",
    ProductionSpeedMultiplier = "production_speed_multiplier",
    ResourceExtractionMultiplier = "resource_extraction_multiplier",
    TradeEfficiencyMultiplier = "trade_efficiency_multiplier",
    TaxRevenueIncrease = "tax_revenue_increase",
    
    HousingIncrease = "housing_increase",
    StorageIncrease = "storage_increase",
    DefenseBonus = "defense_bonus",
    StorageSecurity = "storage_security",
    MilitaryTrainingEfficiency = "military_training_efficiency",
    WaterAccess = "water_access",
    NavigationAid = "navigation_aid",
    CulturalInfluence = "cultural_influence",
    
    //production
    WoodProductionBoost = "wood_production_boost",
    FoodProductionBoost = "food_production_boost",
    ResourceProcessingEfficiency = "resource_processing_efficiency",    
    GoldMiningEfficiency = "gold_mining_efficiency",
    SilverMiningEfficiency = "silver_mining_efficiency",
    GemstoneMiningEfficiency = "gemstone_mining_efficiency",
    JewelryCraftingEfficiency = "jewelry_crafting_efficiency",
    PaperProductionBoost = "paper_production_boost",
    SteelProductionBoost = "steel_production_boost",
    OilExtractionBoost = "oil_extraction_boost",
    PitchProductionBoost = "pitch_production_boost",
    
    // Additional Effects
    FireRiskReduction = "fire_risk_reduction",
    CrimePrevention = "crime_prevention",
    HealthBoost = "health_boost",
    EducationBoost = "education_boost",
    MarketAttractiveness = "market_attractiveness",
    FishingEfficiency = "fishing_efficiency",
    ReligiousInfluence = "religious_influence",
    EntertainmentValue = "entertainment_value",
    LogisticsEfficiency = "logistics_efficiency",
    ConstructionSpeedMultiplier = "construction_speed_multiplier",
    
    // Effects Based on Settlement Types
    TradeNetworkExpansion = "trade_network_expansion",
    FortressDefenseBonus = "fortress_defense_bonus",
    CulturalHeritageBoost = "cultural_heritage_boost",
    DiplomaticInfluence = "diplomatic_influence",
    UndergroundResourceExtraction = "underground_resource_extraction",
    FloatingInfrastructureEfficiency = "floating_infrastructure_efficiency",
    PhasingTechnologyAdvancement = "phasing_technology_advancement",
    RuinsArtifactDiscovery = "ruins_artifact_discovery",
    
    // Effects Based on Travel Events
    StormResistance = "storm_resistance",
    PirateDefenseBonus = "pirate_defense_bonus",
    TsunamiMitigation = "tsunami_mitigation",
    BlizzardSurvivalBoost = "blizzard_survival_boost",
    FogNavigationAid = "fog_navigation_aid",
    OverlordAmbushPreparation = "overlord_ambush_preparation",
    TornadoDamageReduction = "tornado_damage_reduction",
    SeaMonsterAvoidance = "sea_monster_avoidance",
    FriendlyTraderAttraction = "friendly_trader_attraction",
    AbandonedShipDiscovery = "abandoned_ship_discovery",
    InspiringWeatherEffects = "inspiring_weather_effects",
    InspiringCrewMorale = "inspiring_crew_morale",
    MutinyPrevention = "mutiny_prevention",
    CastawayIntegration = "castaway_integration",
    FlotsamRecovery = "flotsam_recovery",
    ElementalDefense = "elemental_defense",
    SageKnowledgeBoost = "sage_knowledge_boost",
    WitchcraftProtection = "witchcraft_protection",
    NativeRelationsImprovement = "native_relations_improvement",
    EarthquakeResistance = "earthquake_resistance",
    TradeEfficiency = "TradeEfficiency",
    WeaponQualityIncrease = "WeaponQualityIncrease",
}
