export enum StructureType {
    // Residential & Basic Infrastructure
    House = "house",
    Hut = "hut",
    Well = "well",
    Woodcutter = "woodcutter",
    Windmill = "windmill",
    Barn = "barn",
  
    // Trade & Storage
    Market = "market",
    Warehouse = "warehouse",
    Docks = "docks",
    Harbor = "harbor",
    Bank = "bank",
  
    // Cultural & Civic Buildings
    Tavern = "tavern",
    Church = "church",
    Cathedral = "cathedral",
    TownHall = "town_hall",
    Palace = "palace",
  
    // Military & Defense
    Barracks = "barracks",
    Tower = "tower",
    Wall = "wall",
    MilitaryAcademy = "military_academy",
  
    // Production Buildings
    Lumberyard = "lumberyard", // Wood
    Brickworks = "brickworks", // Brick
    GrainFarm = "grain_farm", // Grain
    HempFarm = "hemp_farm", // Hemp
    SheepFarm = "sheep_farm", // Wool
    Mine = "mine", // RawMetal, Coal
    Beekeeping = "beekeeping", // Honey
    SaltWorks = "salt_works", // Salt
    Blacksmith = "blacksmith", // MetalGoods
    Brewery = "brewery", // Beer
    Meadery = "meadery", // Mead
    Tailor = "tailor", // Clothing
    Cheesemaker = "cheesemaker", // Cheese
    Fishery = "fishery", // Stockfish
    Tannery = "tannery", // Pelts
    Butchery = "butchery", // Meat
    Vineyard = "vineyard", // Wine
    SpiceMarket = "spice_market", // Spices
    CottonPlantation = "cotton_plantation", // Cotton
    SugarPlantation = "sugar_plantation", // Sugar
    TobaccoPlantation = "tobacco_plantation", // Tobacco
    GoldMine = "gold_mine", // Gold
    SilverMine = "silver_mine", // Silver
    GemstoneMine = "gemstone_mine", // Gemstones
    JewelryWorkshop = "jewelry_workshop", // Jewelry
    Papermill = "papermill", // Paper
    Steelworks = "steelworks", // Steel
    OilRig = "oil_rig", // Oil
    PitchMaker = "pitch_maker", // Pitch
  
    Lighthouse = "lighthouse",
    Totem = "totem",
    Hall = "hall",
    Forge = "forge",
    ClayPit = "clay_pit", // Clay
    MarbleQuarry = "marble_quarry", // Marble
    RubberPlantation = "rubber_plantation", // Rubber
    Glassworks = "glassworks", // Glassware
    TeaPlantation = "tea_plantation", // Tea
    DyeWorks = "dye_works", // Dye
    PotteryWorkshop = "pottery_workshop", // Pottery
    CocoaPlantation = "cocoa_plantation", // Cocoa
    CoffeePlantation = "coffee_plantation", // Coffee
    SaffronFields = "saffron_fields", // Saffron
    PlasticsFactory = "plastics_factory", // PlasticGoods
    AluminiumRefinery = "aluminium_refinery", // Aluminium
    TitaniumFoundry = "titanium_foundry", // Titanium
    Refinery = "refinery", // Fuel
    HydrogenPlant = "hydrogen_plant", // Hydrogen
    OxygenPlant = "oxygen_plant", // Oxygen
    HeliumExtractionFacility = "helium_extraction_facility", // Helium
    FertilizerPlant = "fertilizer_plant", // Fertilizer
    CopperMine = "copper_mine", // Copper
    ManaSlimeHarvester = "mana_slime_harvester", // ManaSlime
    AetherResidueCollector = "aether_residue_collector", // AetherResidue
    SiliconLab = "silicon_lab", // Silicon
    GunpowderMill = "gunpowder_mill", // Gunpowder
    CarbonFiberWorks = "carbon_fiber_works", // CarbonFiber
    ElectronicsFactory = "electronics_factory", // Electronics
    PlasmaGelLab = "plasma_gel_lab", // PlasmaGel
    MachineWorks = "machine_works", // Machinery
    ObsidianQuarry = "obsidian_quarry", // Obsidian
    ChemicalPlant = "chemical_plant", // Chemicals
    GraniteQuarry = "granite_quarry", // Granite
    NitrogenPlant = "nitrogen_plant", // Nitrogen
    CrylithiumSynthesizer = "crylithium_synthesizer", // Crylithium
    VortaniteForge = "vortanite_forge", // Vortanite
    NeptuniumMine = "neptunium_mine", // Neptunium
    AetheriumReactor = "aetherium_reactor", // Aetherium
    SolariumHarvester = "solarium_harvester", // Solarium
    QuantiteSynthesizer = "quantite_synthesizer", // Quantite
    XenoriteExtractor = "xenorite_extractor", // Xenorite
    LuminarChamber = "luminar_chamber", // Luminar
    GravitaniumWell = "gravitanium_well", // Gravitanium
    ObscuriumMine = "obscurium_mine", // Obscurium
    RadiantiteRefinery = "radiantite_refinery", // Radiantite
    PulsariteAccelerator = "pulsarite_accelerator", // Pulsarite
    NovaciteForge = "novacite_forge", // Novacite
    ZephyriumSanctuary = "zephyrium_sanctuary", // Zephyrium
    AstraliteObservatory = "astralite_observatory", // Astralite
    NebulonSynthesizer = "nebulon_synthesizer", // Nebulon
    ChronotiteForge = "chronotite_forge", // Chronotite
    ThermiumRefinery = "thermium_refinery", // Thermium
    ElectritePlant = "electrite_plant", // Electrite
    MagnetariteHarvester = "magnetarite_harvester", // Magnetarite
    DragoniteSanctum = "dragonite_sanctum", // Dragonite
    EmberithKiln = "emberith_kiln", // Emberith
    GlimbriteLab = "glimbrite_lab", // Glimbrite
    TharnaxVault = "tharnax_vault", // Tharnax
    VelunorShrine = "velunor_shrine", // Velunor
    KryntalChamber = "kryntal_chamber", // Kryntal
    ZorviumMine = "zorvium_mine", // Zorvium
    EldrithiumSanctum = "eldrithium_sanctum", // Eldrithium
    MorvexSynthesisLab = "morvex_synthesis_lab", // Morvex
    SylvaranGrove = "sylvaran_grove", // Sylvaran
    DurnaciteForge = "durnacite_forge", // Durnacite
    LuminexCrucible = "luminex_crucible", // Luminex
    VireliumHarvester = "virelium_harvester", // Virelium
    NexaliteMine = "nexalite_mine", // Nexalite
    QuenrilForge = "quenril_forge", // Quenril
    ArcaniteSpire = "arcanite_spire", // Arcanite
    FelbrimAltar = "felbrim_altar", // Felbrim
    XenthiumArray = "xenthium_array", // Xenthium
    MyrralithForge = "myrralith_forge", // Myrralith
    ZephyriteSanctuary = "zephyrite_sanctuary", // Zephyrite
    NexosCore = "nexos_core", // Nexos
    BerilliumReactor = "berillium_reactor" // Berillium
  }
