export enum TravelEventType {
    Storm = "storm",
    PirateAttack = "pirate_attack",
    Tsunami = "tsunami",
    Blizzard = "blizzard",
    Fog = "fog",
    OverlordAmbush = "overlord_ambush",
    Tornado = 'tornado',
    SeaMonster = 'seamonster',
    FriendlyTrader = 'friendly_trader',
    AbandonedShip = 'abandoned_ship',
    InspiringWeather = 'inspiring_weather',
    InspiringCrew = 'inspiring_crew',
    MutinousCrew = 'mutinous_crew',
    Castaway = 'castaway',
    Flodsam = 'flodsam',
    ElementalEncounter = 'elemental_encounter',
    SageEncounter = 'sage_encounter',
    WitchEncounter = 'witch_encounter',
    NativeEncounter = 'native_encounter',
    Earthquake = 'earthquake',
    CulturalFestival = 'cultural_festival',
  }